### ISSUE TITLE
Having trouble running source in browser

### ISSUE THREAD

**Issue by dstack4273** [michbil/hex-works#1]
I'm super unfamiliar with how these libraries interact with one another. Is there any chance you can point me in the right direction with getting started? I'd like to learn how this works a little better.

**Comment by michbil** [comment]
Updated readme.md
Here is changes: 

To start development, you will need NodeJS > 6.0

clone repository, install required libraries
```
cd hex-works
npm install
npm install -g webpack-dev-server
```

To start development server, run
```
webpack-dev-server
```

editor will be live at localhost:8000
